### ISSUE TITLE
WarVOX fails when the IAX2 REGAUTH reply is missing the challenge data

### ISSUE THREAD

**Issue by bajk** [rapid7/warvox#2]
Hello,

I installed and configured warvox, but I'm getting some ruby errors while trying to do wardialing. IAX is configured properly.

D, [2013-05-16T17:23:39.628849 #9429] DEBUG -- : Worker Manager is launching job 3
D, [2013-05-16T17:23:43.540948 #9496] DEBUG -- : Worker 3 dialer is running dialer with parameters {:range=>"06xxxxxxxxxx", :lines=>10, :seconds=>53, :cid_mask=>"SELF"}
/home/ab/.rvm/gems/ruby-1.9.3-p429/gems/librex-0.0.68/lib/rex/proto/iax2/client.rb:193:in `send_regreq_chall_response': undefined method `+' for nil:NilClass (NoMethodError)
	from /home/ab/.rvm/gems/ruby-1.9.3-p429/gems/librex-0.0.68/lib/rex/proto/iax2/call.rb:80:in `register'
	from /home/ab/warvox/bin/iaxrecord.rb:71:in `<main>'

Any ideas what's wrong with my environment or warvox itself? 

Greetings,
AB

**Comment by hmoore-r7** [comment]
This ended up being an issue with 1.8 compatibility (was checking raw bytes vs flags). Fixed now in the rails4 branch.
