### ISSUE TITLE
Asterisk requires certain configuration settings for WarVOX to dial

### ISSUE THREAD

**Issue by hdm** [rapid7/warvox#27]
These are currently:
* nochecksum=yes
* requirecalltoken=no

We should fix WarVOX so these are no longer needed.

**Comment by thewb** [comment]
Note: nochecksum=yes goes in [general] and requirecalltoken=no goes in each trunk in /etc/asterisk/iax.conf

**Comment by hdm** [comment]
Replaced with #36
