### ISSUE TITLE
ERROR: Unable to register with the IAX server

### ISSUE THREAD

**Issue by themayon** [rapid7/warvox#28]
Hello, we have a working rails4 warvox 2.0.0-dev on a machine. When we attempt to make a call, we get this error.

The command  that generates the error is as follows:

/home/warvox/bin/iaxrecord.rb -s 10.0.0.10 -u vox -p vox -o /tmp/ooo -n 036390499
ERROR: Unable to register with the IAX server

Running Asterisk 11.10.2 with the following configuration:

The iax.conf
is [general]
nochecksums=yes
nochecksum=yes

and
[vox]
type=friend
auth=md5
disallow=all
allow=alaw
jitterbuffer=no
trunk=no
requirecalltoken=no
host=dynamic
secret=vox
context=from-internal
port=5003

And when we try to make a call using iaxrecord.vb, we see this on the asterisk console:

Rx-Frame Retry[ No] -- OSeqno: 000 ISeqno: 000 Type: IAX     Subclass: REGREQ 
   Timestamp: 00000ms  SCall: 00001  DCall: 00000 [10.0.0.25:34966]
   USERNAME        : vox
   REFRESH         : 60

Tx-Frame Retry[000] -- OSeqno: 000 ISeqno: 001 Type: IAX     Subclass: REGAUTH
   Timestamp: 00003ms  SCall: 00241  DCall: 00001 [10.0.0.25:34966]
   AUTHMETHODS     : 2
   CHALLENGE       : \x31\x34\x34\x30\x35\x32\x35\x30\x37
   USERNAME        : vox

Tx-Frame Retry[001] -- OSeqno: 000 ISeqno: 001 Type: IAX     Subclass: REGAUTH
   Timestamp: 00003ms  SCall: 00241  DCall: 00001 [10.0.0.25:34966]
   AUTHMETHODS     : 2
   CHALLENGE       : \x31\x34\x34\x30\x35\x32\x35\x30\x37
   USERNAME        : vox

pbx*CLI> 

Any insight here would be appreciated. Possibly is this is a bug in the software?

**Comment by hmoore-r7** [comment]
If you can try running iaxrecord.rb manually with the -d option, this should indicate where the problem is happening on the caller side.

**Comment by hdm** [comment]
Closing due to lack of response
