### ISSUE TITLE
Warvox 2.0.0-dev Authentication fails

### ISSUE THREAD

**Issue by callburn** [rapid7/warvox#34]
I successfully installed warvox 2.0.0-dev on Ubuntu 14.04 running ruby-2.2.3. When I log onto 127.0.0.1:7777 the warvox authentication page loads successfully but when I enter the username admin and password warvox, the system says the password is incorrect. I accessed the warvox.conf file and changed the username and password but the system still says the password is incorrect. I'm not sure where I'm getting it all wrong. Thanks

**Comment by zeknox** [comment]
Sounds like you have not created an admin account as required with the following command:
<pre>$ bin/adduser admin</pre>

This should create an admin account in the db, and post the randomly generated creds to the screen to use.

**Comment by callburn** [comment]
You made me look in the right direction, user admin already existed so I used bin/resetpw and I'm now up and running
