### ISSUE TITLE
ERROR: Unable to register with the IAX server 

### ISSUE THREAD

**Issue by naiduharish-r** [rapid7/warvox#35]
I have got warvox installed and I'm using Vitality as VOIP provider. To regsiter with  IAX server I used the GUI(using update provider) with the following settings from Vitality .

Register Server : sip35.vitelity.net (66.241.99.208)
Outbound Server : outbound.vitelity.net
Port : 4569
Login : login_name
Password : XXXXXXX

Now when I try to make a call, I get the below error 'Unable to register with the IAX server'

`Errors: []
D, [2016-01-07T11:44:39.937909 #7709] DEBUG -- : Worker Manager is launching job 8
D, [2016-01-07T11:44:41.431639 #8321] DEBUG -- : Worker 8 dialer is running dialer with parameters {:range=>"971504840737", :lines=>1, :seconds=>53, :cid_mask=>"SELF"}
ERROR: Unable to register with the IAX server
D, [2016-01-07T11:44:53.956804 #7709] DEBUG -- : Worker Manager is clearing 1 completed jobs
`

I'm not sure where I'm getting it all wrong. Thanks!

**Comment by naiduharish-r** [comment]
I also tried the below

`root@kali:/home/warvox/bin# ./iaxrecord.rb -s 66.241.99.208 -u username -p xxxxxx -o /tmp/warvox-error1 -n 971559727226 -d
ERROR: Unable to register with the IAX server`

**Comment by hdm** [comment]
The IAX2 stack within WarVOX is hand-rolled. Any chance you could shoot me a pcap of the traffic? I can test against my vitelity account in a bit as well (x [at] hdm.io | https://keybase.io/hdm/ )

**Comment by hdm** [comment]
The cause is #36
