### ISSUE TITLE
Issue during bundle Install

### ISSUE THREAD

**Issue by Ka0s-M0nk3y** [rapid7/warvox#41]
I have ran through the install process and when i try to bundle install i keep getting hung up on Fetching git://github.com/hdm/reportable.git

and get the following error

fatal: unable to connect to github.com:
github.com[0: 192.30.252.120]: errno=Connection timed out

Retrying git clone 'git://github.com/hdm/reportable.git' "/var/lib/gems/2.2.0/cache/bundler/git/reportable-7af7c60f377f6e0041f90a3566e0de8c5b3005a3" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/hdm/reportable.git' "/var/lib/gems/2.2.0/cache/bundler/git/reportable-7af7c60f377f6e0041f90a3566e0de8c5b3005a3" --bare --no-hardlinks --quiet` in directory /pentest/warvox has failed.

**Comment by Ka0s-M0nk3y** [comment]
Looks like i fixed the issue i had to update the gem file with gem 'reportable', :require => 'saulabs/reportable'

**Comment by hdm** [comment]
The saulabs version is not compatible, the issue you ran into seems to be a temporary network error.

**Comment by Ka0s-M0nk3y** [comment]
Interesting do you know what would have caused the error?  Once I replaced that line I was able to download the other gems with no issue.

**Comment by Ka0s-M0nk3y** [comment]
I think I found the issue. Looks like in the gem file it is using this 
" gem 'reportable', :git => 'git://github.com/hdm/reportable.git', :require => 'saulabs/reportable' " 

and instead needs to be using this 

"gem 'reportable', git: 'https://github.com/hdm/reportable.git', :require => 'saulabs/reportable' "

After doing this it installed everything correctly. Let me know if this is correct.

**Comment by hdm** [comment]
Ah, that is a better way to specify it. The git:// path may not be allowed out of some networks.
