### ISSUE TITLE
Unable to install the tool on Kali

### ISSUE THREAD

**Issue by nipundev** [rapid7/warvox#43]
Hello @hdm 

Hope you are doing well. Me, not so well. I want to wardial the heck out of some client, so I wanted Warvox for the same. However, the tool just completely refuses to install on Kali2. 

So here's what I did. I followed the entire install guide on the Github. I have struggled with Ruby and Gem issues but have resolved it. Now, I am stuck on this step to _make database_, which gives me the following error:
`root@office:/home/warvox# make database
Checking the database..
RAILS_ENV=production bundle exec rake db:migrate
/usr/lib/x86_64-linux-gnu/ruby/2.3.0/continuation.so: warning: callcc is obsolete; use Fiber instead
/usr/lib/ruby/vendor_ruby/rex/proto/http/server.rb:83: warning: key "jpeg" is duplicated and overwritten on line 84
/usr/lib/ruby/vendor_ruby/rex/proto/smb/exceptions.rb:11: warning: key 0 is duplicated and overwritten on line 12
/usr/lib/ruby/vendor_ruby/rex/proto/smb/exceptions.rb:17: warning: key 128 is duplicated and overwritten on line 18
rake aborted!
LoadError: cannot load such file -- less
/var/lib/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:101:in `require'
/var/lib/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:101:in `<module:Sprockets>'
/var/lib/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:3:in `<top (required)>'
/var/lib/gems/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:5:in `require'
/var/lib/gems/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/sass-rails-4.0.5/lib/sass/rails/railtie.rb:1:in `require'
/var/lib/gems/2.3.0/gems/sass-rails-4.0.5/lib/sass/rails/railtie.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/sass-rails-4.0.5/lib/sass/rails.rb:11:in `require'
/var/lib/gems/2.3.0/gems/sass-rails-4.0.5/lib/sass/rails.rb:11:in `<top (required)>'
/var/lib/gems/2.3.0/gems/sass-rails-4.0.5/lib/sass-rails.rb:1:in `require'
/var/lib/gems/2.3.0/gems/sass-rails-4.0.5/lib/sass-rails.rb:1:in `<top (required)>'
/home/warvox/config/application.rb:10:in `<top (required)>'
/home/warvox/Rakefile:4:in `require'
/home/warvox/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
Makefile:20: recipe for target 'database' failed
make: *** [database] Error 1'
Now, I have googled the heck out of every single line and even Stackoverflow.com is unable to help me here. Thus, I have come to seek aid from you. Please help !

Thanks, 

N

**Comment by hdm** [comment]
Is this a fresh checkout of WarVOX from master?

**Comment by nipundev** [comment]
Yes it is. Cloned today.

Nipun Gupta
Building a future, together.

**Comment by hdm** [comment]
You need to run ``bundle install``, the error: ``LoadError: cannot load such file less`` shows that the dependencies are missing.

**Comment by HollandOates** [comment]
Ok, I'm trying to install this into my Kali2 instance, because I just learned about WarVox in my GCIH course. I have a customer wanting me to wardial them. Bundle Installer is trying to install Puma 3.6.0. I have 3.9.1 installed. What do I need to tweak to get it to stop choking on puma 3.6.0?

**Comment by hdm** [comment]
No idea unfortunately

**Comment by donfanning** [comment]
@HollandOates I would use rvm with the rails addition and pin your WarVox install to a particular version like 1.9.3 which had a fairly long shelf life or you can forego all of it and use a docker containerized version.  https://hub.docker.com/r/beardyjay/warvox/ appears to be fairly complete without using it myself.

**Comment by nipundev** [comment]
Yup, I am ended up using the Docker machine too.

Best,

Nipun

On Aug 7, 2017, 8:27 PM -0700, Don Fanning <notifications@github.com>, wrote:

@HollandOates<https://github.com/hollandoates> I would use rvm with the rails addition and pin your WarVox install to a particular version like 1.9.3 which had a fairly long shelf life or you can forego all of it and use a docker containerized version. https://hub.docker.com/r/beardyjay/warvox/ appears to be fairly complete without using it myself.
