### ISSUE TITLE
Which version is recommended?

### ISSUE THREAD

**Issue by elimisteve** [rapid7/warvox#44]
The README states,

> DO NOT USE WARVOX 2.0.0-dev YET!

Which version of WarVOX do you recommend using?

I've read [impressive articles](https://www.security-database.com/toolswatch/WarVox-1-for-auditing-telephone.html) about WarVOX 1.0 from a few years ago. Should I git checkout an old 1.x commit, or do something else? Thanks.

**Comment by hdm** [comment]
This is a case of bit rot; the older version is affected by Rails vulnerabilities. The new version is better, but not quite working as intended yet, and is in maintenance twilight at the moment (might be behind on security issues, etc).

**Comment by hdm** [comment]
With the release of Rails 5.0, versions of Rails prior to 4.2 are no longer getting security updates, which means a lot more churn work for WarVOX to get back to a supported baseline again.

**Comment by elimisteve** [comment]
I see. Okay thanks!
