### ISSUE TITLE
Warvox stops working on Kali due to Ruby issues

### ISSUE THREAD

**Issue by nipundev** [rapid7/warvox#45]
Hi @hdm 

At this point I have tried various flavors of kali, it's updates, gems, rubies, etc, but I am unable to get Warvox working. Some update in Kali broke it. Can you please help ?
```
root@kali:/home/warvox# bin/warvox.rb 

[*] Starting WarVOX on http://127.0.0.1:7777/

I, [2016-07-13T14:25:27.142033 #17717]  INFO -- : WarVOX is starting up...
I, [2016-07-13T14:25:27.142629 #17717]  INFO -- : Worker Manager has PID 17719
I, [2016-07-13T14:25:27.142704 #17717]  INFO -- : Web Server has PID 17719
Exiting
/usr/lib/ruby/vendor_ruby/rack/handler.rb:54:in `default': uninitialized constant Rack::Handler::REQUEST_METHOD (NameError)
	from /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/server.rb:268:in `server'
	from /var/lib/gems/2.3.0/gems/railties-4.1.15/lib/rails/commands/server.rb:112:in `print_boot_information'
	from /var/lib/gems/2.3.0/gems/railties-4.1.15/lib/rails/commands/server.rb:64:in `start'
	from /var/lib/gems/2.3.0/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	from /var/lib/gems/2.3.0/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /var/lib/gems/2.3.0/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /var/lib/gems/2.3.0/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-4.1.15/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/warvox/script/rails:6:in `require'
	from /home/warvox/script/rails:6:in `<top (required)>'
	from bin/warvox.rb:104:in `load'
	from bin/warvox.rb:104:in `<main>'
```
Thanks, 

N

**Comment by hdm** [comment]
Switch to RVM for Ruby, make sure you are using git master, and keep in mind that WarVOX is obsolete at the moment due to the unsupported Rails version.

**Comment by nipundev** [comment]
Thanks ! I am definitely using master branch, but I still think it is WarVOX dev.

**Comment by hdm** [comment]
The 2.0.0 branch never got a stable release, since keeping up with Rails took more time than it made sense to spend on WarVOX (used just enough to drive an email once a month).

**Comment by nipundev** [comment]
That sucks, I thought it was a slick tool as described by my buddy last year. Any alternate tools you suggest to use for mass dialing ? I have an IAX2 server and everything set-up. 
Thanks a lot for rapid replies :).

Date: Wed, 13 Jul 2016 21:50:35 -0700

**Comment by hdm** [comment]
https://wardial.us/software/ lists some options. WarVOX will likely work for you with a bit more pipe banging (rvm ruby, `make verify`, etc), but it isn't safe to put on a public interface at the moment.

**Comment by nipundev** [comment]
Hey HD,
One last question since I am out of ideas, what is a stable build for WarVOX ? And OS ?
I can contribute my results here with detailed installation instructions.
Thanks,
Nipun

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.9.8&pv=9.3.1&source=email_footer_2]
On Thu, Jul 14, 2016 at 8:08 AM, HD Moore <notifications@github.com> wrote:
https://wardial.us/software/ [https://wardial.us/software/] lists some options. WarVOX will likely work for you with a bit more pipe banging (rvm ruby, make verify , etc), but it isn't safe to put on a public interface at the moment.

**Comment by hdm** [comment]
Ubuntu 14.04 / 16.04 with the master branch from Git and a recent Ruby version using RVM
