### ISSUE TITLE
Postgres Problem

### ISSUE THREAD

**Issue by rknikiting** [rapid7/warvox#46]
sorry, newbie here.

root@kali:/home/warvox# sudo su - postgres
postgres@kali:~$ createuser -s warvox
createuser: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

I'm stuck. please help. 
Kali Linux 2016.1

**Comment by hdm** [comment]
You need to start the database first (/etc/init.d/postgresql start)

**Comment by XSecr3t** [comment]
I have same problems
