### ISSUE TITLE
undefined local variable or method?

### ISSUE THREAD

**Issue by qiMakur** [rapid7/warvox#50]
I installed WarVOX on Linuxmint (uname -v: #47-Ubuntu SMP) and everything went smoothly. No errors. I pulled up the web interface and ran a couple of test scans, again, everything ran smoothly with no errors. Today I tried to start warvox.rb and got the following errors. (I tried to investigate and resolve the error but I have no experience with ruby and quickly got in over my head.)

$ bin/warvox.rb

[*] Starting WarVOX on http://127.0.0.1:7777/

I, [2016-10-11T09:58:13.416389 #4598]  INFO -- : WarVOX is starting up...
I, [2016-10-11T09:58:13.416776 #4598]  INFO -- : Worker Manager has PID 4600
I, [2016-10-11T09:58:13.416832 #4598]  INFO -- : Web Server has PID 4600
/opt/warvox/bin/rails:2:in `<top (required)>': undefined local variable or method `__dir__' for main:Object (NameError)
	from bin/warvox.rb:104:in `load'
	from bin/warvox.rb:104:in `<main>'
/opt/warvox/config/boot.rb:1:in `<top (required)>': undefined local variable or method `__dir__' for main:Object (NameError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /opt/warvox/bin/worker_manager.rb:21:in `<top (required)>'
	from bin/warvox.rb:91:in `load'
	from bin/warvox.rb:91:in `<main>'

It seems like the solution should be simple enough, cause it was working. Can anyone give me a nudge in the right direction?

**Comment by cheeyeo** [comment]
Hi @qiMakur 

warvox has been recently upgraded to Rails 5 so you need at least Ruby 2.2 and above to run it.

Can you share your version of ruby and rails here from your Gemfile?

**Comment by hdm** [comment]
Closing due to lack of response after two weeks.
