### ISSUE TITLE
Dialing Issues

### ISSUE THREAD

**Issue by sans1241** [rapid7/warvox#52]
Hi @hdm ,

I have installed warvox V2.0.0 successfully in my ubuntu machine 16.04.2 LTS (GNU/Linux 4.8.0-36-generic x86_64) and bought some credits from https://voip.ms. But when I dial the numbers it is showing me Ring Time '0', Busy 'No' and seconds '0'. The numbers are valid phone numbers, but i have no idea what went wrong here. Could you please help me on this.

Please note only 80 and 443 ports are open in my ubuntu machine.

Thank you.

**Comment by hdm** [comment]
Hello! It may be worth capturing the iax2 traffic with wireshark and looking for any obvious errors. Another approach would be to run the bin/iaxrecord utility manually with the -d parameter.

**Comment by hdm** [comment]
Closing due to lack of response, please re-open if you have time to diagnose the problem with a pcap or the -d parameter to iaxrecord.
