### ISSUE TITLE
WarVox  running issue

### ISSUE THREAD

**Issue by SHAW900** [rapid7/warvox#54]
Hi Dear,

 I need  your help if possible i am trying to use warvox and i already installed and its done successfully but issue i am facing is when i dial call through War Project its always say JOB COMPLETED but no call made i try several time but same issue if you please help me out its really appreciated .

i am posting error as well 

Errors: []
D, [2017-05-01T14:35:49.530311 #2449] DEBUG -- : Worker Manager is launching job 25
D, [2017-05-01T14:35:53.266594 #2502] DEBUG -- : Worker 25 dialer is running dialer with parameters {:range=>"0046313088976", :lines=>10, :seconds=>53, :cid_mask=>"SELF"}
ERROR: Errno::ENOMEM Cannot allocate memory - '/opt/warvox/bin/iaxrecord.rb' '-s' 'myip ' '-u' 'myuser' '-p' 'mypass' '-c' '001-12345678' '-o' '/tmp/rawfile20170501-2502-su8fw9' '-n' '0046313088976' '-l' '53' ["/opt/warvox/lib/warvox/jobs/dialer.rb:116:in `popen'", "/opt/warvox/lib/warvox/jobs/dialer.rb:116:in `block in start'"] 00123456789 {:name=>"test3", :id=>3, :port=>4570, :host=>"104.196.193.91 ", :user=>"my user", :pass=>"mypass", :lines=>20}
D, [2017-05-01T14:36:00.555532 #2449] DEBUG -- : Worker Manager is clearing 1 completed jobs

thank you for your time and help.

waiting for reply

Regards
Moris

**Comment by hdm** [comment]
Your system needs more memory, preferably 8Gb+:
```ERROR: Errno::ENOMEM Cannot allocate memory```
