### ISSUE TITLE
ERROR: Unable to register with the IAX server

### ISSUE THREAD

**Issue by SHAW900** [rapid7/warvox#55]
Hi all,

first of all i want to thanks to HDM for great help on my last issue regarding memory and so quick reply thank you  :)

Now issue is i installed everything as mentioned in installation guide but now i when try to dial is say **## ERROR: Unable to register with the IAX server**  i am not using any other software like ASTERISK i  am using only WARVOX on server .

so please  help me out how i can manage to solve this and start making calls.

thanks in advance

Errors: []
D, [2017-05-02T18:41:08.163625 #12784] DEBUG -- : Worker Manager is launching job 4
D, [2017-05-02T18:41:14.365774 #12815] DEBUG -- : Worker 4 dialer is running dialer with parameters {:range=>"xxxxxxxxxxxxxxxx", :lines=>10, :seconds=>53, :cid_mask=>"15555558                                888"}
ERROR: Unable to register with the IAX server
ERROR: Unable to register with the IAX server

**Comment by SHAW900** [comment]
anybody there to help !!!!!!!!

**Comment by hdm** [comment]
As mentioned in the other issue, please provide a pcap of the communication between WarVOX and your IAX server.

**Comment by SHAW900** [comment]
Thank you for your reply  i just downloaded pcap can i ask you how i can share log with you i mean can you  please explain me regarding sharing logs through pcap.

regards

**Comment by hdm** [comment]
Hi! You can send it via email - x@hdm.io

**Comment by SHAW900** [comment]
Hello hdm ,


thank you for reply please find the attachment of pcap file also im sending an email to you.

Regards

**Comment by SHAW900** [comment]
as you can download from here as well:


h**# ttps://files.fm/u/msbtekyd#_**

**Comment by hdm** [comment]
This appears to be SSH traffic, not the IAX2 communication between WarVOX and the asterisk server you are talking to.

**Comment by SHAW900** [comment]
how i can fix this  ? whats solution for this ?

**Comment by hdm** [comment]
Probably not, sorry!

**Comment by SHAW900** [comment]
So shall I re-install this? there should be something which makes this works !!
thank you for your help and time :)
