### ISSUE TITLE
OBi200

### ISSUE THREAD

**Issue by jdmcwhinnie** [rapid7/warvox#57]
Hello i have been trying to set up my OBi200 for use with Warvox, but with no luck.
My OBi200 is using my google voice number and is functional
I just am  having difficulty figuring out just what to do...
I have read all the OBi200 manuals and tutorials on possibly setting up for PBX etc.

but to no avail.

Please help.  Thank you

**Comment by hdm** [comment]
WarVOX is designed to talk to a IAX2 provider like Asterisk, the OBi200 doesn't seem useful in this regard.
