### ISSUE TITLE
ERROR: Unable to register with the IAX server

### ISSUE THREAD

**Issue by kamitelco** [rapid7/warvox#59]
D, [2018-04-12T00:56:04.515033 #28232] DEBUG -- : Worker Manager is launching job 7
D, [2018-04-12T00:56:09.332549 #28249] DEBUG -- : Worker 7 dialer is running dialer with parameters {:range=>"34632802425\n34931796817\n34602344145\n34632198686", :lines=>10, :seconds=>53, :cid_mask=>"1555555XXXX"}
ERROR: Unable to register with the IAX server

**Comment by hdm** [comment]
WarVOX is unsupported at the moment, sorry!
